### ISSUE TITLE
When toggling Fire Widget, only display fires that triggered a notification

### ISSUE THREAD

**Issue by aprins-innovate** [USEPA/R9-Widgets#87]
Toggling the widget should only displays fires that triggered a notification and are present in the widget interface.

The fire layers in the layerlist should still display all fires.

**Comment by tbock** [comment]
We don't maintain a point service for the fires that triggered a notification.  Its only a poly service.  So we'd have to try to set up a definition query for those services.  Not sure I agreed with this particularly since there is a zoom button for each fire. @aprins-innovate . 

I am investigating why there are so many fires in the widget right now.  Perhaps thats part of the issue?

**Comment by aprins-innovate** [comment]
This was a request from CH and some other managers who don't want to see all the fires on the map when the widget is on. It's pretty busy this way (even when there are fewer overall fires) and hard to differentiate. They only want to see the ones that matter to them.

**Comment by tbock** [comment]
so what should happen if the fire layers are already on and they open the widget? @aprins-innovate

**Comment by aprins-innovate** [comment]
If possible it should switch over to only show notified fires. @tbock
